# PURPOSE OF THIS DOCUMENT______________________________________________________
# This file is supposed to test all of the features and ambiguious cases
# written in the TOML specification. Can be used for other projects as well.
# ______________________________________________________________________________

# STRINGS
       basic  = "This is a basic string."
basic2 = "Another one with a \nnewline, /ttab a \"quote\"."

multilinebasic = """
This is \


  a basic \
    string."""

multilinebasic2 = """\
       This is \
       a basic \
       string.\
       """
